# Typus Roles Configuration File
#
# Use the README file as a reference to customize settings.

admin:
  LineItem: create, read, update, delete
  Order: create, read, update, delete
  Product: create, read, update, delete
